feat(searchresultstore): adding ability to pre select variant options
searchspring/snap pull request #1010
Opened 2024-03-13 18:40 UTC by chrisFrazier77

2024-04-16 17:50 UTC, korgon requested changes
Can we put events into a separate file to clean up constructor (eg. configureSnapFeatures)


We decided on this name/spacing and interface:
```
searchspring.fire('controller/selectVariantOptions', {
  controllers,
  options,
});
```

Lets use explicit exact match or regex only (no string regex):
```
controllers: ['search', /^recommend_/]
```

Needs Readme.

2024-04-25 17:36 UTC, korgon requested changes
Global events will be nice!

2024-04-25 17:36 UTC, korgon commented on packages/snap-store-mobx/src/Search/Stores/SearchResultStore.test.ts
> +		it('can configured to preselect certain variants', () => {
Does this test actually verify that the preselected values are actually selected...?

2024-04-25 17:36 UTC, korgon commented on packages/snap-store-mobx/src/Search/Stores/SearchResultStore.ts
> +			// select first available for each selection
This comment not quite right :|

2024-04-25 17:36 UTC, korgon commented on packages/snap-store-mobx/src/Search/Stores/SearchResultStore.ts
> +					if (typeof preferedOptions == 'object') {
Preferred `Array.isArray()` if that is what we are expecting.

2024-04-25 17:36 UTC, korgon commented on packages/snap-store-mobx/src/Search/Stores/SearchResultStore.ts
> +					if (typeof preferedOptions == 'object') {
Logic could be simplified if we just always convert to array, or make it require an array.

2024-05-02 20:15 UTC, chrisFrazier77 commented on packages/snap-preact/src/setupEvents.test.tsx
> +								},
shouldnt, but thats why i wanted that in the test, to make sure it handled skipping banner types correctly

2024-05-03 14:13 UTC, korgon commented on packages/snap-preact/README.md
> +### event-manager
I think the property name should match up with the subheading here - `eventManager`.

2024-05-03 14:13 UTC, korgon commented on packages/snap-store-mobx/src/Search/Stores/SearchResultStore.ts
> +	public update(variantData: VariantData[], config?: VariantConfig) {
If this function is called externally (in middleware for example), will the user need to pass the `config` parameter used at construction to get the same settings?

2024-05-03 19:03 UTC, korgon approved these changes

2024-05-03 21:39 UTC, merged