feat(tracker): add currency context, add transactionTotal to order tr…
searchspring/snap pull request #1078
Opened 2024-06-20 16:35 UTC by dkonieczek

…ansaction payload

2024-06-20 21:10 UTC, chrisFrazier77 submitted a review, later dismissed

2024-06-21 20:52 UTC, korgon requested changes
A few changes requested in review, but additionally, there should be a way to set the currency via the [script context variables](https://searchspring.github.io/snap/#/integration-context) (similar to `shopperId`).

Perhaps something like this:
```
<script src="https://snapui.searchspring.io/[your_site_id]/bundle.js">
    currency = { code: "USD" };
</script>
```

2024-06-21 20:52 UTC, korgon commented on packages/snap-tracker/src/Tracker.ts
> +		if (this.globals.currency) {
`this.globals.currency` should be of type:
```
{
  code: string;
}
```

2024-06-21 20:52 UTC, korgon commented on packages/snap-tracker/src/Tracker.ts
> +	setCurrency = (currency: string): void => {
This function should take an object as the param:
```
{
  code: string;
}
```

2024-06-21 20:52 UTC, korgon commented on packages/snap-tracker/src/Tracker.ts
> +			view: (data: CartViewEvent, siteId?: string, currency?: string): BeaconEvent | undefined => {
I think we can remove the currency param here and instead assume that the currency has already been set on the context.

2024-06-21 20:52 UTC, korgon commented on packages/snap-tracker/src/Tracker.ts
> +			transaction: (data: OrderTransactionData, siteId?: string, currency?: string): BeaconEvent | undefined => {
I think we can remove the currency param here and instead assume that the currency has already been set on the context.

2024-06-26 16:00 UTC, korgon approved these changes
Looks good.

2024-06-26 16:14 UTC, merged