feat(recommendationinstantiator): add cart param to recs context
searchspring/snap pull request #426
Opened 2022-03-29 15:02 UTC by dkonieczek

2022-03-29 17:58 UTC, korgon requested changes
I forgot to include a new attribute for click tracking: `ss-track-cart-view` - in v3 when an element is clicked with this attribute it simply tells all recommendations components to refresh/reload.

Another thing I failed to add to the task (sorry) - was the whole bubbling code that checks for parents of the clicked target to see if they have attributes of interest. This is an issue when a span was clicked that was inside of a button/a tag that has the attribute.
https://github.com/searchspring/ajax-catalog-v3/blob/master/src/internal_modules/attribute-tracking.js#L4

2022-03-29 17:58 UTC, korgon commented on packages/snap-preact/src/Instantiators/RecommendationInstantiator.tsx
> +					(this.config.services?.tracker || this.tracker).cookies.cart.set(cartContents);
I think we ought to be setting `this.tracker` (along with other services) to the config services (if provided) during construction.

```
(this.config.services?.tracker || this.tracker).cookies.cart.set(cartContents);
```
Should become:
```
this.tracker.cookies.cart.set(cartContents);
```

It looks like we are doing this for services throughout the instantiator - but perhaps it is a good time to refactor and make this better.

2022-03-29 18:33 UTC, korgon requested changes
Perfect! This should get things up to date.

Last thing... there are likely tests and/or documentation that should be updated with these changes... can you please ensure they are included in the PR?

2022-04-07 18:41 UTC, korgon requested changes
Couple things in comments...
Also I find it a bit confusing that we have both `cart` and `shopper.cart` as recommendation contexts. I wonder if we should modify this a bit?
https://github.com/searchspring/snap/blob/628694c0b920f97959f202c536698839cc5d757d/docs/INTEGRATION.md?plain=1#L61-L75

2022-04-07 18:41 UTC, korgon commented on docs/INTEGRATION.md
> +| cart | array (or function that returns an array) of current cart skus | all | optional method of setting cart contents |
Looks like we may be missing `shopper` here?

2022-04-07 18:41 UTC, korgon commented on packages/snap-tracker/src/Tracker.ts
> +					`href`,
What is it we are doing with the `href` here?

2022-04-12 14:35 UTC, dkonieczek commented
Turns out the RecommendationInstantiator doesn't even used shopper.cart, it only uses shopper.id so I removed it from the documentation and example code.

2022-04-12 14:39 UTC, korgon approved these changes

2022-04-12 15:29 UTC, merged