Mobile sidebar
searchspring/snap pull request #881
Opened 2023-08-31 22:35 UTC by chrisFrazier77

2023-09-01 15:36 UTC, korgon requested changes
Looking good - few adjustments in comments.

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/MobileSidebar/MobileSidebar.tsx
I like how you have separated the header, body and footer content (title, sidebar, cta-wrapper), but I think we ought to change these class names:

`ss__mobile-sidebar__title` => `ss__mobile-sidebar__header`
`ss__mobile-sidebar__sidebar` => `ss__mobile-sidebar__body`
`ss__mobile-sidebar__cta-wrapper` => `ss__mobile-sidebar__footer` 

Other changes I think would be good would be changing the prop names around a bit, starting with the header and footer.

`hideHeader` (instead of 'hideTitle')
`hideFooter` (no equivalent exists currently)

I think some consistency in naming could be helpful for some of the other props as well. For example `clearButtonText` and `hideClearAllButton` are referring to the same thing, but are named slightly differently. Additionally, for some of these buttons, an icon might be nice to have.

`openButtonText` (instead of 'slideoutButtonText')
`openButtonIcon` (instead of 'iconOpen')

`closeButtonText` (doesn't currently exist, but seems reasonable to want 'close' instead of icon here)
`closeButtonIcon` (instead of 'iconClose')
`hideCloseButton`

`clearButtonText`
`clearButtonIcon` (doesn't currently exist, but seems reasonable to want an icon and no text or both)
`hideClearButton` (instead of 'hideClearAllButton')

`applyButtonText`
`applyButtonIcon` (doesn't currently exist, but seems reasonable to want an icon and no text or both)
`hideApplyButton`

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/MobileSidebar/MobileSidebar.tsx
> +						<span>{titleText}</span>
I think we may want to have a classname on this element (and maybe use an H tag?) - eg: `ss__mobile-sidebar__header__title`

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/MobileSidebar/MobileSidebar.test.tsx
Missing tests for button functionality - specifically the apply and clear buttons in the footer.

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/MobileSidebar/readme.md
Will need changes after standardization of prop names.

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/Sidebar/Sidebar.stories.tsx
> +			description: 'hides the sidebar title component',
Not _really_ a component...  /shrug

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/Sidebar/Sidebar.stories.tsx
> +			description: 'hides the sidebar per page component',
per page -> PerPage

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/Sidebar/Sidebar.stories.tsx
> +			description: 'hides the sidebar sort by component',
sort by -> SortBy

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/Sidebar/Sidebar.tsx
> +				{!hideTitle && <h4 className="ss__sidebar__title">{titleText}</h4>}
This shown when the page is loading, might want to wrap the entire thing in some check?

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Templates/Search/Search.tsx
> +						<MobileSidebar controller={controller} {...subProps.MobileSidebar} />
The positioning here is awkward and could be better - but something we can adjust later.

<img width="504" alt="image" src="https://github.com/searchspring/snap/assets/5060400/5a37c84a-e91e-4955-a7e2-53d39586d7bd">

2023-09-01 15:36 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/MobileSidebar/MobileSidebar.stories.tsx
> +	return <MobileSidebar {...args} controller={controller} />;
For this default example in storybook, I think changing the openButtonText could be helpful; maybe something like 'click me' or 'click to open filters' or similar to make it more obvious.

2023-09-08 17:01 UTC, korgon requested changes
With the changes to the Button component to include an icon, we will possibly want/need a wrapper around the button text. Without the wrapper it is impossible to use flex ordering on the button contents (eg. want to make the icon first). Although, I noticed that using an `order: -1` on the icon element does this also... However, styling just this text (without affecting the icon) would be more difficult without a wrapper.

2023-09-08 17:01 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/Sidebar/Sidebar.tsx
Thinking about things... Should the left Banner component be here? Perhaps a prop to hide it as well?

2023-09-11 22:41 UTC, chrisFrazier77 commented on packages/snap-preact-components/src/components/Organisms/Sidebar/Sidebar.tsx
TBD

2023-09-12 15:41 UTC, korgon approved these changes

2023-09-12 15:41 UTC, merged