ada improvements - focus trap
searchspring/snap pull request #948
Opened 2023-11-21 20:14 UTC by chrisFrazier77

2023-12-01 21:05 UTC, korgon requested changes

2023-12-07 21:52 UTC, chrisFrazier77 commented on packages/snap-preact-components/src/hooks/useA11y.tsx
I personally like that its in the same hook.

2023-12-14 23:40 UTC, korgon requested changes

2023-12-14 23:40 UTC, korgon commented on packages/snap-preact-components/src/hooks/useA11y.tsx
Leaving them together is fine.

2023-12-14 23:40 UTC, korgon commented on packages/snap-preact-components/src/components/Molecules/RadioList/RadioList.tsx
Similar to `List` comments, we can probably leverage the aria roles / attributes here to get our context as well as handle the "x of y" and label stuff without `aria-label` usage.

I was leveraging this documentation when I was experimenting:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/

For this component I was using `radiogroup` role on the `ul` wrapping the options:
```
role="radiogroup" aria-label="sorting options"
```

^ "sorting options" above should likely come from the `titleText`? Or maybe a new optional prop?

Additionally each option likely needs to have some attributes:
```
role="option"
aria-selected={selected}
```

2023-12-14 23:40 UTC, korgon commented on packages/snap-preact-components/src/components/Molecules/RadioList/RadioList.tsx
^ some of this isn't fully tested - like the selected bit, it conflicts with the `Radio` component, so that might need some rework.

2023-12-14 23:40 UTC, korgon commented on packages/snap-preact-components/src/components/Organisms/MobileSidebar/MobileSidebar.tsx
I think this still needs some work - please spend some more time using a screen reader and the keyboard to find more improvements here.

Some things that are awkward upon testing are:

1. After opening the slideout by using the enter key, the escape key doesn't do anything
2. After opening the slideout and then tabbing, the screen reader reads way too much
3. After opening the slideout and then tabbing, pressing the escape key doesnt return the focus to the button that opened it

2023-12-14 23:40 UTC, korgon commented on packages/snap-preact-components/src/components/Templates/Autocomplete/Autocomplete.tsx
The screen reader experience in this component feels like it could use more love. It may just be the macOS screen reader that operates a bit differently.

Some awkward experiences:

1. When tabbing into the suggestions, some text is repeated "popular searches popular searches"
2. sometimes it reads _way_ too much when tabbing around, for example when tabbing to the "show more results" it then starts reading **all the things**
3. many of the things in AC are "options" and would perhaps function better as such

2023-12-14 23:41 UTC, korgon commented on packages/snap-preact-components/src/hooks/useA11y.tsx
> +					}
I think we could get rid of them all and just use callback to handle everything.

2023-12-15 16:31 UTC, chrisFrazier77 commented on packages/snap-preact-components/src/components/Atoms/Button/Button.tsx
> +		...additionalProps,
it was to add an aria-label in MobileSidebar

2023-12-26 22:25 UTC, korgon commented on packages/snap-preact-components/src/components/Atoms/Button/Button.tsx
> +		...additionalProps,
Makes me think we should just add this to all components... 🤔

2023-12-27 16:08 UTC, korgon commented on packages/snap-preact-components/src/components/Templates/Autocomplete/Autocomplete.tsx
This can. be addressed later when we have more direction.

2023-12-27 16:11 UTC, korgon approved these changes
Working better. I have a few commits to push for small things. After that I will merge.

2023-12-27 16:14 UTC, merged